### ISSUE TITLE
Service overview

### ISSUE THREAD

**Issue by JessicaLoers** [Rick1Marques/booking-app#1]
## Value proposition

As a provider
I want to have a list of my services
so that I can have an overview of the services that I offer

## Description

![Image](https://user-images.githubusercontent.com/107452548/268228705-59ead03c-bfd2-46b9-89b7-45652ee3f931.png)

## Acceptance criteria

- [ ] On the homepage the provider has a list of his/her services
    - [ ] The list has two columns
    - [ ] The list is vertically scrollable

- [ ] Every displayed service shows 
    - [ ] name of the service
    - [ ] picture or icon of the service
    - [ ] little price tag

- [ ] if there is no service yet the page will show the following message "...currently no services"
- [ ] if there was an error loading the data the page will show the following message "404"   

## Tasks

- [ ] Create the feature branch "service-list"
- [ ] Create a database in MongoDb
- [ ] Fetch the list of the current service from MongoDb
  - [ ] Implement the "errorHandling" logic to display an error message if there is 
    an issue loading the data from MongoDb
  - [ ] Check if there is a service of the list. If not, display a message saying no services available

- [ ] Create the component Service which renders
    - [ ] name of the service
    - [ ] picture or icon of the service
    - [ ] little price tag

- [ ] Create the component "ServiceList" which maps trough the fetched list of services and renders 
  the Service component for each service 

- [ ] Create the component "TitleApp"

- [ ] Create the component "TitlePage"

- [ ] Render the components in the index.js
