### ISSUE TITLE
User's Profile

### ISSUE THREAD

**Issue by PZhu888** [Rick1Marques/booking-app#10]
## Value proposition

As a user
I want to have my own profile
so that I can check my balance and get access to my collection and selling list

## Description

![Image](https://user-images.githubusercontent.com/132745980/268996629-e385ccda-88a4-4f59-8a4f-328778fc8f51.png)

## Acceptance criteria

- [ ] The user can see a nav bar on every page of the app which shows a home icon and a profile icon
    - By clicking the home icon the user will be directed to the "Marketplace" page
    - By clicking the profile icon the user will be directed to her/his profile

- [ ] The "User's Profile" page shows the following information:
    - Name of the user
    - Image of the user
    - Credits of the user
    - A link to the collection of the user
    - A link to the selling list of the user

## Tasks

- [ ] List the tasks that need to be performed within the dev team

**Comment by ahohnsen** [comment]
Hey you,


Please, keep in mind that we do not want to include items, which do not have a function yet.
If I have seen it correctly, at this point you won't have the user's collection and selling list. Therefore these items should not be part of this user story. Please adjust the following:

- Scribble: remove the links to the user's collection and selling list
- Value proposition: needs an update as well 👇 

_As a user
I want to have my own profile
so that I can check my current balance_

**Comment by shrocket** [comment]
Hello!
Thank you for letting me have a look at your app. I have some comments:
- In general, this looks great! I was super impressed with how professional your presentation was during our public sprint review (and especially with Berna's fantastic English skills!)!
- In English, the word is spelled "bazaar". With a total of 3 As! :)
- According to your acceptance criteria, there is a "home icon." There is no home icon, there is the word "Marketplace."
- According to your acceptance criteria, there is a "user icon." There is no user icon, there is the word "MyProfile."
- Clicking on "Marketplace" works the way it is supposed to.
- Clicking on "MyProfile" produces on "Loading..."
- I looked at your deployment as though I were using an iPhone SE, in that view, the nav bar covered content at the bottom of all pages.
Please let me know if you have any questions about these comments! I'm always happy to help.
Best, Shawn 🚀

**Comment by DavevonH** [comment]
Hi Shawn,
Thank you for the review! We know about the Icons and nav bar covering the items. We will add and adjust it later when doing a bit of styling for project.
Yesterday we have fixed the "MyProfile" link. Now it should work! Maybe you can have a look at it again? 😃

**Comment by shrocket** [comment]
It does work! (and Nute Gunray!!!)
Technically, because the acceptance criteria says "icon," and you're not using icons, this still shouldn't pass QA, but you know that and have mentioned it, so I see no reason to be any more pedantic than I have already been (am currently being?).
Please post another QA in the channel, tag me, and I'll greenlight it ASAP!
