### ISSUE TITLE
Service detail

### ISSUE THREAD

**Issue by JessicaLoers** [Rick1Marques/booking-app#2]
## Value proposition

As a provider
I want to have a detail page of each service
so that I see more information about it

## Description

![Image](https://user-images.githubusercontent.com/107452548/268233587-0815f31d-7238-41d2-9825-c0a969550ce1.png)

## Acceptance criteria

- [ ] On the detail page the provider has specs infos of each service

- [ ] Every displayed service shows 
    - [ ] name of the service
    - [ ] duration
    - [ ] picture or icon of the service
    - [ ] price tag
    - [ ] description

- [ ] if there was an error loading the data the page will show the following message "404"   

## Tasks

- [ ] Create the feature branch "detail-page"
- [ ] Fetch the list of the current service from MongoDb
  - [ ] Implement the "errorHandling" logic to display an error message if there is an issue loading the data from MongoDb

- [ ] Create the services details page pages/services/[id].js
- [ ] Add the Link component to navigate back to the homepage
- [ ] Add the Link component to navigate to the details page
- [ ] Create the component Service which receive an "id" and renders
    - [ ] name of the service
    - [ ] duration
    - [ ] picture or icon of the service
    - [ ] price tag
    - [ ] description

**Comment by JessicaLoers** [comment]
Well done ✨ 
There are some suggestions that I would like to share with you.

**Value Proposition:**
**As a** provider
**I want to** **access detailed information about**  of each service
👉 _Put the focus on the service and not on the detail page_
**so that I** can provide potential customers with comprehensive and enticing descriptions of what I offer.
👉 _This is the real goal we are aiming for with this feature_

**Acceptance criteria**
- Please specify how the user/provider **can reach** the detail view of the respective service.
- Please explain how the user/provider **can leave** this detail view. Maybe with a "Back to Overview" link.

**Tasks**
The tasks must be updated after the adjustment of the acceptance criteria. 

**Wireframe Description**
The Wireframe Description must be updated after the adjustment of the acceptance criteria.

**Comment by PZhu888** [comment]
Thank you very much! We already adjusted the user story according to your suggestions.
