### ISSUE TITLE
Add service

### ISSUE THREAD

**Issue by JessicaLoers** [Rick1Marques/booking-app#3]
## Value proposition

As a provider
I want to be able to add/delete services
so that I can offer new services to the customers

## Description

![Image](https://user-images.githubusercontent.com/107452548/268282334-2df3f9f2-1043-4136-b63f-6d0da94745e9.png)

## Acceptance criteria

- [ ] On the service overview page the provider has the opportunity to add a service via a Link
 - [ ] it links to a new page where he can add a new service

- [ ] on the new Add service page he can add following service details 
    - [ ] name of the service
    - [ ] description
    - [ ] duration
    - [ ] price
    - [ ] picture or icon of the service

- [ ] after providing all the information he can add the information 
 for the service by pressing the submit button
  

## Tasks

- [ ] List the tasks that need to be performed within the dev team

**Comment by JessicaLoers** [comment]
Nice work. Very good that you separated the user story add and delete. 💚

_Some suggestions from the User Story Polizei 👮_

**Value proposition**
**As a** provider
**I want to** be able to add services 
👉 _Please remove the delete here._ 
**so that I** can offer new services to the customers

**Acceptance criteria**

 - [ ] it links to a new page where he can add a new service
⬇️
- [ ] Clicking the "Add" link redirects to a new page where the provider can add a new service.
👉 _More concise and gender neutral 😁._ 

- [ ]  on the new Add service page he can add following service details
⬇️
- [ ]  on the "Add Service" page the provider can add following service details
👉 _More concise and gender neutral 😁._ 

Further Acceptance Criteria you should think about:
- what happens if the user/provider tries to submit an empty form?
- what happens if the user/provider does not fill in all fields (i.e. which are mandatory fields)? 
- what happens after the form is submitted?
 - is the user/provider redirected to a page? If so, which one?
 - is there a hint for the user/provider when the entry has been submitted successfully?
 - is there a hint for the user/provider if the entry was not submitted successfully?
- where can the new entry be seen?

Please adapt the wireframe accordingly and formulate the task accordingly. 💚
