### ISSUE TITLE
Delete service

### ISSUE THREAD

**Issue by JessicaLoers** [Rick1Marques/booking-app#4]
## Value proposition

As a provider
I want to be able to delete services
so I can remove the services that I no longer offer

## Description

![Image](https://user-images.githubusercontent.com/107452548/268287677-8393bb59-c5b2-494c-aa3d-f5be87643b33.png)

## Acceptance criteria

- [ ] On the detail page the provider has the opportunity to delete a service with a button
- [ ] The provider should get a confirm pop-up before the service is removed
- [ ] Then the provider can select between "Yes" or "No" buttons
   - [ ] if he presses yes the service gets deleted and he gets redirected to the overview page
   - [ ] if he presses no he's gonna stay on the detail page
  

## Tasks

- [ ] List the tasks that need to be performed within the dev team

**Comment by JessicaLoers** [comment]
**Well-o-well 👏**
_Please keep in mind that we want to imply the functionality of deleting first and then that of editing._

Therefore adjust the wireframe (without the "Edit service" Option )
