### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by DavevonH** [Rick1Marques/booking-app#6]
## Value proposition

As a user
I want to see a list of current starship for sale
so that I can have an overview of the market

## Description

![Image](https://user-images.githubusercontent.com/140090722/268687974-aa21dbbc-10db-4b9f-abd5-0244f06e6010.png)

## Acceptance criteria

- [ ] On the top of the page the user can see the title of the app "Starship Basar" and the page name "Marketplace"

- [ ] Then the user can see a list of starships which are available for sale
    
    - The list has two columns
    - The list is vertically scrollable

- [ ] Each displayed Starship shows:

    - Name of the Starship
    - Picture of the Starship

-  [ ] If there is a loading error, the page will show the following message "Sorry, something went
  wrong. 404 Page not found!" 

## Tasks

- [ ] List the tasks that need to be performed within the dev team

**Comment by ahohnsen** [comment]
Well done 👍 

Just a tiny recommendation:

It's great that you will implement an error message, if there is a problem loading the data. I think, it would be nice to also give instructions to the user in that message, e.g.: Please try again later. 🙂

**Comment by e-rmkt** [comment]
Very well done! Looks great and works as expected! Can't wait to buy my first spaceship! ;D
