### ISSUE TITLE
Starship Details

### ISSUE THREAD

**Issue by DavevonH** [Rick1Marques/booking-app#7]
## Value proposition

As a user
I want to have access to detailed information about each Starship
so that I can inform myself whether this Starship is the one i want to purchase and if I can afford it

## Description

![Image](https://user-images.githubusercontent.com/140090722/268901060-9a6aecdc-689b-4f02-9269-2b3b0b1cc492.png)

## Acceptance criteria

-  [ ] On the "Marketplace" the user has the opportunity to click on the Starship picture which
  links to the "Starship Details" page where the user can see more details about the Starship 

- [ ] The displayed Starship shows:
    - image    
    - name
    - model
    - manufacturer
    - max_atmosphering_speed
    - passengers
    - cargo_capacity
    - starship_class
    - price
    - name of the seller
    - image of the seller
   
- [ ] The user can go back to the "Marketplace" with a link

- [ ] If there is a loading error, the page will show the following message "Sorry, something went
  wrong. 404 Page not found!"   

## Tasks

- [ ] List the tasks that need to be performed within the dev team

**Comment by ahohnsen** [comment]
Heyho!

Very well written. I just would like you to update your scribble:

- The scribble should include real content and no placeholder text (e.g. no "starship 1", "user 2" etc.)
- The scribble does not include all the information you are listing in your acceptance criteria: model, manufacturer, max_atmosphering_speed, passengers, cargo_capacity, starship_class
👉🏼 Please be a bit more specific here. The scribble helps to visualize how the entire thing should look like later on.
