### ISSUE TITLE
Buy Button

### ISSUE THREAD

**Issue by PZhu888** [Rick1Marques/booking-app#8]
## Value proposition

As a user
I want to be able to buy a starship
so that I can add it to my collection

## Description

![Image](https://user-images.githubusercontent.com/132745980/268924684-039b42e8-900b-4243-a9e2-a57833e64ec7.png)

## Acceptance criteria

- [ ] On the "Starship Details" page the user can buy a starship by clicking the "Buy" button
- [ ] After buying the starship the user will be redirected to the "Marketplace"
- [ ] The purchased starship will no longer be visible on the "Marketplace" and it will automatically be added to 
  the user's Collection
- [ ] The price of the starship will be subtracted from the buying user's credits and will be added to the seller's credits

## Tasks

- [ ] List the tasks that need to be performed within the dev team

**Comment by NicoleHoerner** [comment]
Looks good!
